// Datos de los diez sitios emblemáticos de Nariño que se visitan en el mundo.
// Cada entrada define posición, radios de proximidad/colisión, descripción y el
// nombre del builder 3D (`builderFn`) que lo construye en `world/siteBuilders.js`.
export const SITES = [
  {
    id: 'lajas',
    name: 'Santuario de Las Lajas',
    municipio: 'Ipiales',
    position: { x: 0, z: 62 },
    rotation: 0,
    scale: 1.5,
    proximityRadius: 22,
    solidRadius: 10,
    description: 'Basílica neogótica levantada sobre un puente de piedra de unos 50 metros de altura, en el cañón del río Guáitara. Construida entre 1916 y 1949 en el lugar donde, según la tradición, la Virgen apareció sobre una roca.',
    builderFn: 'buildLajas',
  },
  {
    id: 'cocha',
    name: 'Laguna de La Cocha',
    municipio: 'El Encano (Pasto)',
    position: { x: 34.1, z: 46.9 },
    rotation: 0,
    scale: 1.3,
    proximityRadius: 20,
    solidRadius: 10,
    description: 'Segundo lago natural más grande de Colombia, a unos 2.760 m de altitud. En su interior está la Isla La Corota, Santuario de Flora y Fauna. En la orilla destacan las casas de techos altos de estilo alpino del corregimiento de El Encano.',
    builderFn: 'buildCocha',
  },
  {
    id: 'galeras',
    name: 'Volcán Galeras',
    municipio: 'Pasto',
    position: { x: 62.8, z: 20.4 },
    rotation: 0,
    scale: 1.6,
    proximityRadius: 26,
    solidRadius: 14,
    description: 'Volcán activo de unos 4.276 m que domina la ciudad de San Juan de Pasto. Es uno de los volcanes más vigilados de Colombia y un símbolo del paisaje nariñense.',
    builderFn: 'buildGaleras',
  },
  {
    id: 'cumbal',
    name: 'Volcán Cumbal',
    municipio: 'Cumbal',
    position: { x: 57.1, z: -18.5 },
    rotation: 0,
    scale: 1.6,
    proximityRadius: 26,
    solidRadius: 14,
    description: 'El nevado más alto de Nariño, con unos 4.764 m de altitud. Su cima cubierta de hielo es un referente del resguardo indígena de los Pastos en el suroccidente del departamento.',
    builderFn: 'buildCumbal',
  },
  {
    id: 'azufral',
    name: 'Laguna Verde de Azufral',
    municipio: 'Túquerres',
    position: { x: 40, z: -55 },
    rotation: 0,
    scale: 1,
    proximityRadius: 16,
    solidRadius: 8,
    description: 'Laguna que ocupa el cráter del volcán Azufral, a unos 3.970 m. Su característico color verde turquesa se debe a los minerales de azufre disueltos en el agua.',
    builderFn: 'buildAzufral',
  },
  {
    id: 'catedral',
    name: 'Catedral de Pasto',
    municipio: 'Pasto',
    position: { x: 0, z: -56 },
    rotation: 0,
    scale: 1.4,
    proximityRadius: 20,
    solidRadius: 10,
    description: 'Templo del centro histórico de San Juan de Pasto, de fachada republicana con dos torres. Forma parte del rico patrimonio religioso de la ciudad, conocida por sus iglesias y su Carnaval de Negros y Blancos.',
    builderFn: 'buildCatedral',
  },
  {
    id: 'planada',
    name: 'Reserva La Planada',
    municipio: 'Ricaurte',
    position: { x: -37.6, z: -51.8 },
    rotation: 0,
    scale: 1,
    proximityRadius: 17,
    solidRadius: 9,
    description: 'Reserva natural de bosque de niebla en territorio del pueblo Awá, reconocida por su enorme biodiversidad de aves, orquídeas y anfibios. Un refugio del piedemonte costero nariñense.',
    builderFn: 'buildPlanada',
  },
  {
    id: 'morro',
    name: 'El Morro de Tumaco',
    municipio: 'Tumaco',
    position: { x: -56.1, z: -18.2 },
    rotation: 0,
    scale: 1,
    proximityRadius: 16,
    solidRadius: 8,
    description: 'Formación rocosa con un arco natural en la costa pacífica de San Andrés de Tumaco. Es el emblema de la ciudad, rodeado de playas, palmeras y el mar abierto.',
    builderFn: 'buildMorro',
  },
  {
    id: 'chiles',
    name: 'Volcán Chiles',
    municipio: 'Cumbal',
    position: { x: -63.7, z: 20.7 },
    rotation: 0,
    scale: 1.55,
    proximityRadius: 25,
    solidRadius: 13,
    description: 'Volcán de unos 4.748 m situado en la frontera entre Colombia y Ecuador. Sus páramos y aguas termales lo rodean de un paisaje altoandino único.',
    builderFn: 'buildChiles',
  },
  {
    id: 'sandona',
    name: 'Sandoná — Paja Toquilla',
    municipio: 'Sandoná',
    position: { x: -35.9, z: 49.3 },
    rotation: 0,
    scale: 1,
    proximityRadius: 15,
    solidRadius: 7,
    description: 'Municipio de la región del Guáitara famoso por la artesanía en paja toquilla: sombreros y tejidos elaborados a mano. Sus casas coloniales blancas con techo de teja son parte de su encanto.',
    builderFn: 'buildSandona',
  },
];
